export const hotelData = [
  {
    id: 1,
    name: "Sunrise Suites",
    country: "China",
    location: "Beijing",
    description: "A luxurious stay with breathtaking views.",
    price: 50.0,
    comments: "The view is stunning, and the service was exceptional.",
    rating: 3.5,
    rooms: 50,
    amenities: ["Wi-Fi"],
    image: "https://t7.baidu.com/it/u=1595072465,3644073269&fm=193&f=GIF",
  },
  {
    id: 2,
    name: "Harmony Inn",
    country: "USA",
    location: "Los Angeles",
    description:
      "Located in the bustling city center, perfect for business travelers.",
    price: 54.08,
    comments: "Great location for exploring the city, with modern facilities.",
    rating: 3.5,
    rooms: 51,
    amenities: ["Wi-Fi", "Parking"],
    image: "https://img95.699pic.com/photo/50086/5089.jpg_wh860.jpg",
  },
  {
    id: 3,
    name: "Ocean Breeze Hotel",
    country: "France",
    location: "Lyon",
    description: "Experience serenity by the riverside.",
    price: 58.16,
    comments: "A peaceful escape with excellent local cuisine.",
    rating: 3.6,
    rooms: 52,
    amenities: ["Wi-Fi", "Parking", "Pool"],
    image:
      "https://tse1-mm.cn.bing.net/th/id/OIP-C.d9W2O41mcuRTZBvtmYvEkwHaGv?w=223&h=203&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 4,
    name: "Mountain Retreat",
    country: "Japan",
    location: "Hokkaido",
    description: "Wake up to ocean waves at this cozy hotel.",
    price: 62.24,
    comments: "The ocean view was spectacular, and the staff were kind.",
    rating: 3.6,
    rooms: 53,
    amenities: ["Wi-Fi", "Parking", "Pool", "Gym"],
    image:
      "https://tse4-mm.cn.bing.net/th/id/OIP-C.7teBmXE4sOTkKiuiKx5jQAHaEZ?w=277&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 5,
    name: "Urban Oasis",
    country: "Australia",
    location: "Sydney",
    description: "A hidden gem nestled in the mountains.",
    price: 66.33,
    comments: "Charming and serene atmosphere with outstanding scenery.",
    rating: 3.6,
    rooms: 54,
    amenities: ["Wi-Fi", "Parking", "Pool", "Gym", "Spa"],
    image:
      "https://tse4-mm.cn.bing.net/th/id/OIP-C.gWW5NQScvcQ3uGVEyENLSgHaE8?w=278&h=185&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 6,
    name: "Riverfront Lodge",
    country: "India",
    location: "Mumbai",
    description: "Stay near famous attractions with luxurious amenities.",
    price: 70.41,
    comments: "A must-stay for visitors, close to attractions.",
    rating: 3.7,
    rooms: 55,
    amenities: ["Wi-Fi"],
    image:
      "https://tse4-mm.cn.bing.net/th/id/OIP-C.KeynD96WK5hx-x26b4ZTUwHaFj?w=249&h=187&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 7,
    name: "Golden Gate Resort",
    country: "Germany",
    location: "Frankfurt",
    description:
      "An urban retreat with modern design and vibrant nightlife nearby.",
    price: 74.49,
    comments: "Perfect for those looking for nightlife and comfort.",
    rating: 3.7,
    rooms: 56,
    amenities: ["Wi-Fi", "Parking"],
    image:
      "https://tse1-mm.cn.bing.net/th/id/OIP-C.46POzquKcdpZe-WYU8uLSgHaF6?w=244&h=195&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 8,
    name: "Cultural Haven Hotel",
    country: "Brazil",
    location: "Salvador",
    description:
      "Immerse yourself in the rich local culture while enjoying modern comforts.",
    price: 78.57,
    comments: "A great location near historical sites, with friendly staff.",
    rating: 3.7,
    rooms: 57,
    amenities: ["Wi-Fi", "Parking", "Pool"],
    image:
      "https://tse2-mm.cn.bing.net/th/id/OIP-C.ZdRPmexf8Cm34R7F3Mg1jgHaE8?w=272&h=182&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 9,
    name: "Starlight Grand",
    country: "South Africa",
    location: "Cape Town",
    description: "A high-end hotel ideal for business and leisure.",
    price: 82.65,
    comments: "Top-notch service with luxurious amenities.",
    rating: 3.7,
    rooms: 58,
    amenities: ["Wi-Fi", "Parking", "Pool", "Gym"],
    image:
      "https://tse1-mm.cn.bing.net/th/id/OIP-C.1Te4qAHTlLHzjrS24Jh0IwHaE7?w=252&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 10,
    name: "Forest Whisper Inn",
    country: "Canada",
    location: "Vancouver",
    description: "A cozy stay near famous festivals.",
    price: 86.73,
    comments: "Perfect for winter vacations with charming interiors.",
    rating: 3.8,
    rooms: 59,
    amenities: ["Wi-Fi", "Parking", "Pool", "Gym", "Spa"],
    image:
      "https://tse1-mm.cn.bing.net/th/id/OIP-C.jpfFeBvzQ8L9L2N-fOprNQHaE6?w=295&h=196&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 11,
    name: "Sunrise Suites",
    country: "China",
    location: "Guangzhou",
    description: "A luxurious stay with breathtaking views.",
    price: 90.82,
    comments: "The view is stunning, and the service was exceptional.",
    rating: 3.8,
    rooms: 60,
    amenities: ["Wi-Fi"],
    image:
      "https://tse3-mm.cn.bing.net/th/id/OIP-C.dAP0oHp4F565zYntTHzGPwHaFB?w=266&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 12,
    name: "Harmony Inn",
    country: "USA",
    location: "San Francisco",
    description:
      "Located in the bustling city center, perfect for business travelers.",
    price: 94.9,
    comments: "Great location for exploring the city, with modern facilities.",
    rating: 3.8,
    rooms: 61,
    amenities: ["Wi-Fi", "Parking"],
    image:
      "https://tse2-mm.cn.bing.net/th/id/OIP-C.HIIOCtN4iU2PKT6byGIQkgHaLG?w=89&h=89&c=1&rs=1&qlt=90&r=0&dpr=1.3&pid=InlineBlock",
  },
  {
    id: 13,
    name: "Ocean Breeze Hotel",
    country: "France",
    location: "Paris",
    description: "Experience serenity by the riverside.",
    price: 98.98,
    comments: "A peaceful escape with excellent local cuisine.",
    rating: 3.9,
    rooms: 62,
    amenities: ["Wi-Fi", "Parking", "Pool"],
    image:
      "https://tse2-mm.cn.bing.net/th/id/OIP-C.sy9HNduviAodflV7QyKr4wHaEk?w=253&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 14,
    name: "Mountain Retreat",
    country: "Japan",
    location: "Osaka",
    description: "Wake up to ocean waves at this cozy hotel.",
    price: 103.06,
    comments: "The ocean view was spectacular, and the staff were kind.",
    rating: 3.9,
    rooms: 63,
    amenities: ["Wi-Fi", "Parking", "Pool", "Gym"],
    image:
      "https://tse2-mm.cn.bing.net/th/id/OIP-C.mPnEVziKC2z_xL7Em5VwKAHaE8?w=278&h=186&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 15,
    name: "Urban Oasis",
    country: "Australia",
    location: "Brisbane",
    description: "A hidden gem nestled in the mountains.",
    price: 107.14,
    comments: "Charming and serene atmosphere with outstanding scenery.",
    rating: 3.9,
    rooms: 64,
    amenities: ["Wi-Fi", "Parking", "Pool", "Gym", "Spa"],
    image:
      "https://tse1-mm.cn.bing.net/th/id/OIP-C.CIbI2jkmSgDgWBn-cefVywHaE8?w=279&h=186&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 16,
    name: "Riverfront Lodge",
    country: "India",
    location: "Kolkata",
    description: "Stay near famous attractions with luxurious amenities.",
    price: 111.22,
    comments: "A must-stay for visitors, close to attractions.",
    rating: 4.0,
    rooms: 65,
    amenities: ["Wi-Fi"],
    image:
      "https://tse2-mm.cn.bing.net/th/id/OIP-C.DuLPzaBbAQzXXVZ_IcyRYQHaEK?w=329&h=185&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 17,
    name: "Golden Gate Resort",
    country: "Germany",
    location: "Berlin",
    description:
      "An urban retreat with modern design and vibrant nightlife nearby.",
    price: 115.31,
    comments: "Perfect for those looking for nightlife and comfort.",
    rating: 4.0,
    rooms: 66,
    amenities: ["Wi-Fi", "Parking"],
    image:
      "https://tse4-mm.cn.bing.net/th/id/OIP-C.9ABfApZylR2VQy8pBSXv7wHaGV?w=215&h=184&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 18,
    name: "Cultural Haven Hotel",
    country: "Brazil",
    location: "S\u00e3o Paulo",
    description:
      "Immerse yourself in the rich local culture while enjoying modern comforts.",
    price: 119.39,
    comments: "A great location near historical sites, with friendly staff.",
    rating: 4.0,
    rooms: 67,
    amenities: ["Wi-Fi", "Parking", "Pool"],
    image:
      "https://tse1-mm.cn.bing.net/th/id/OIP-C.HdypEmsTwmLJLayuP83NZAHaEW?w=299&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 19,
    name: "Starlight Grand",
    country: "South Africa",
    location: "Durban",
    description: "A high-end hotel ideal for business and leisure.",
    price: 123.47,
    comments: "Top-notch service with luxurious amenities.",
    rating: 4.1,
    rooms: 68,
    amenities: ["Wi-Fi", "Parking", "Pool", "Gym"],
    image:
      "https://tse1-mm.cn.bing.net/th/id/OIP-C.idMxuY2XylYItE3nj9AYTwHaE3?w=241&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 20,
    name: "Forest Whisper Inn",
    country: "Canada",
    location: "Calgary",
    description: "A cozy stay near famous festivals.",
    price: 127.55,
    comments: "Perfect for winter vacations with charming interiors.",
    rating: 4.1,
    rooms: 69,
    amenities: ["Wi-Fi", "Parking", "Pool", "Gym", "Spa"],
    image:
      "https://tse3-mm.cn.bing.net/th/id/OIP-C.p4mJsxr1fMCiauf9fE31zAHaFl?w=209&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 21,
    name: "Sunrise Suites",
    country: "China",
    location: "Beijing",
    description: "A luxurious stay with breathtaking views.",
    price: 131.63,
    comments: "The view is stunning, and the service was exceptional.",
    rating: 4.1,
    rooms: 70,
    amenities: ["Wi-Fi"],
    image:
      "https://tse1-mm.cn.bing.net/th/id/OIP-C.GiGbMDlIH2ZGesU5AdDTHAHaE8?w=278&h=185&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 22,
    name: "Harmony Inn",
    country: "USA",
    location: "Los Angeles",
    description:
      "Located in the bustling city center, perfect for business travelers.",
    price: 135.71,
    comments: "Great location for exploring the city, with modern facilities.",
    rating: 4.1,
    rooms: 71,
    amenities: ["Wi-Fi", "Parking"],
    image:
      "https://tse1-mm.cn.bing.net/th/id/OIP-C.BiqPfdxwPsRZGcfF-pA3EAHaFj?w=254&h=190&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 23,
    name: "Ocean Breeze Hotel",
    country: "France",
    location: "Lyon",
    description: "Experience serenity by the riverside.",
    price: 139.8,
    comments: "A peaceful escape with excellent local cuisine.",
    rating: 4.2,
    rooms: 72,
    amenities: ["Wi-Fi", "Parking", "Pool"],
    image:
      "https://tse2-mm.cn.bing.net/th/id/OIP-C.GO7k4tqBE_RIRoQhtL2a4gHaLH?w=158&h=186&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 24,
    name: "Mountain Retreat",
    country: "Japan",
    location: "Hokkaido",
    description: "Wake up to ocean waves at this cozy hotel.",
    price: 143.88,
    comments: "The ocean view was spectacular, and the staff were kind.",
    rating: 4.2,
    rooms: 73,
    amenities: ["Wi-Fi", "Parking", "Pool", "Gym"],
    image:
      "https://tse3-mm.cn.bing.net/th/id/OIP-C.wXkQsTkkDcvrk_S0P6JcLQHaE8?w=296&h=197&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 25,
    name: "Urban Oasis",
    country: "Australia",
    location: "Sydney",
    description: "A hidden gem nestled in the mountains.",
    price: 147.96,
    comments: "Charming and serene atmosphere with outstanding scenery.",
    rating: 4.2,
    rooms: 74,
    amenities: ["Wi-Fi", "Parking", "Pool", "Gym", "Spa"],
    image:
      "https://tse2-mm.cn.bing.net/th/id/OIP-C.W_LFB620STVC2s1rri0S6gHaE8?w=259&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 26,
    name: "Riverfront Lodge",
    country: "India",
    location: "Mumbai",
    description: "Stay near famous attractions with luxurious amenities.",
    price: 152.04,
    comments: "A must-stay for visitors, close to attractions.",
    rating: 4.3,
    rooms: 75,
    amenities: ["Wi-Fi"],
    image:
      "https://tse4-mm.cn.bing.net/th/id/OIP-C.DaFGzDAuxnwQBlhM8JPr3wAAAA?w=203&h=140&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 27,
    name: "Golden Gate Resort",
    country: "Germany",
    location: "Frankfurt",
    description:
      "An urban retreat with modern design and vibrant nightlife nearby.",
    price: 156.12,
    comments: "Perfect for those looking for nightlife and comfort.",
    rating: 4.3,
    rooms: 76,
    amenities: ["Wi-Fi", "Parking"],
    image:
      "https://tse1-mm.cn.bing.net/th/id/OIP-C.uYRJ8zrUZ9CibCVDQ56yfAHaFj?w=226&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 28,
    name: "Cultural Haven Hotel",
    country: "Brazil",
    location: "Salvador",
    description:
      "Immerse yourself in the rich local culture while enjoying modern comforts.",
    price: 160.2,
    comments: "A great location near historical sites, with friendly staff.",
    rating: 4.3,
    rooms: 77,
    amenities: ["Wi-Fi", "Parking", "Pool"],
    image:
      "https://tse2-mm.cn.bing.net/th/id/OIP-C.EpdwRefzcPAzcnLNN3XjSwHaE8?w=306&h=204&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 29,
    name: "Starlight Grand",
    country: "South Africa",
    location: "Cape Town",
    description: "A high-end hotel ideal for business and leisure.",
    price: 164.29,
    comments: "Top-notch service with luxurious amenities.",
    rating: 4.4,
    rooms: 78,
    amenities: ["Wi-Fi", "Parking", "Pool", "Gym"],
    image:
      "https://tse3-mm.cn.bing.net/th/id/OIP-C.JSDqHyMK7tNWuua-W1nlawHaFv?w=248&h=192&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 30,
    name: "Forest Whisper Inn",
    country: "Canada",
    location: "Vancouver",
    description: "A cozy stay near famous festivals.",
    price: 168.37,
    comments: "Perfect for winter vacations with charming interiors.",
    rating: 4.4,
    rooms: 79,
    amenities: ["Wi-Fi", "Parking", "Pool", "Gym", "Spa"],
    image:
      "https://tse4-mm.cn.bing.net/th/id/OIP-C.jdWcIcfkfq4LbhJ2xpAsrwHaHa?w=174&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 31,
    name: "Sunrise Suites",
    country: "China",
    location: "Guangzhou",
    description: "A luxurious stay with breathtaking views.",
    price: 172.45,
    comments: "The view is stunning, and the service was exceptional.",
    rating: 4.4,
    rooms: 80,
    amenities: ["Wi-Fi"],
    image:
      "https://tse2-mm.cn.bing.net/th/id/OIP-C.ISwbzSKqbyQUyLGlL7gxkwAAAA?w=286&h=191&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 32,
    name: "Harmony Inn",
    country: "USA",
    location: "San Francisco",
    description:
      "Located in the bustling city center, perfect for business travelers.",
    price: 176.53,
    comments: "Great location for exploring the city, with modern facilities.",
    rating: 4.4,
    rooms: 81,
    amenities: ["Wi-Fi", "Parking"],
    image:
      "https://tse3-mm.cn.bing.net/th/id/OIP-C.aznxQxRAnaX5_doLnenQJgHaE8?w=264&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 33,
    name: "Ocean Breeze Hotel",
    country: "France",
    location: "Paris",
    description: "Experience serenity by the riverside.",
    price: 180.61,
    comments: "A peaceful escape with excellent local cuisine.",
    rating: 4.5,
    rooms: 82,
    amenities: ["Wi-Fi", "Parking", "Pool"],
    image:
      "https://tse4-mm.cn.bing.net/th/id/OIP-C.7SfLdSEsagwW7giuQhMAnwHaHa?w=184&h=184&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 34,
    name: "Mountain Retreat",
    country: "Japan",
    location: "Osaka",
    description: "Wake up to ocean waves at this cozy hotel.",
    price: 184.69,
    comments: "The ocean view was spectacular, and the staff were kind.",
    rating: 4.5,
    rooms: 83,
    amenities: ["Wi-Fi", "Parking", "Pool", "Gym"],
    image:
      "https://tse3-mm.cn.bing.net/th/id/OIP-C.yXN71Dc0qbXkHowGWhTpDQHaFj?w=245&h=184&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 35,
    name: "Urban Oasis",
    country: "Australia",
    location: "Brisbane",
    description: "A hidden gem nestled in the mountains.",
    price: 188.78,
    comments: "Charming and serene atmosphere with outstanding scenery.",
    rating: 4.5,
    rooms: 84,
    amenities: ["Wi-Fi", "Parking", "Pool", "Gym", "Spa"],
    image:
      "https://tse2-mm.cn.bing.net/th/id/OIP-C.4nPo_IkpxtMIvqGyUSvWdQHaHa?w=156&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 36,
    name: "Riverfront Lodge",
    country: "India",
    location: "Kolkata",
    description: "Stay near famous attractions with luxurious amenities.",
    price: 192.86,
    comments: "A must-stay for visitors, close to attractions.",
    rating: 4.6,
    rooms: 85,
    amenities: ["Wi-Fi"],
    image:
      "https://tse2-mm.cn.bing.net/th/id/OIP-C.Fub6EjJiITagJF-A8S3PBAHaHa?w=194&h=187&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 37,
    name: "Golden Gate Resort",
    country: "Germany",
    location: "Berlin",
    description:
      "An urban retreat with modern design and vibrant nightlife nearby.",
    price: 196.94,
    comments: "Perfect for those looking for nightlife and comfort.",
    rating: 4.6,
    rooms: 86,
    amenities: ["Wi-Fi", "Parking"],
    image:
      "https://tse3-mm.cn.bing.net/th/id/OIP-C.Ktbsj5gKA0fVc7D_kMkhxAHaFj?w=223&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 38,
    name: "Cultural Haven Hotel",
    country: "Brazil",
    location: "S\u00e3o Paulo",
    description:
      "Immerse yourself in the rich local culture while enjoying modern comforts.",
    price: 201.02,
    comments: "A great location near historical sites, with friendly staff.",
    rating: 4.6,
    rooms: 87,
    amenities: ["Wi-Fi", "Parking", "Pool"],
    image:
      "https://tse3-mm.cn.bing.net/th/id/OIP-C.XTolt75DdZ5I0EPrWltxKQHaFj?w=208&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 39,
    name: "Starlight Grand",
    country: "South Africa",
    location: "Durban",
    description: "A high-end hotel ideal for business and leisure.",
    price: 205.1,
    comments: "Top-notch service with luxurious amenities.",
    rating: 4.7,
    rooms: 88,
    amenities: ["Wi-Fi", "Parking", "Pool", "Gym"],
    image:
      "https://tse4-mm.cn.bing.net/th/id/OIP-C.Nx0Cjve4ZWUN5_oggp13KwHaEJ?w=276&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 40,
    name: "Forest Whisper Inn",
    country: "Canada",
    location: "Calgary",
    description: "A cozy stay near famous festivals.",
    price: 209.18,
    comments: "Perfect for winter vacations with charming interiors.",
    rating: 4.7,
    rooms: 89,
    amenities: ["Wi-Fi", "Parking", "Pool", "Gym", "Spa"],
    image:
      "https://tse2-mm.cn.bing.net/th/id/OIP-C.GZTPIBl00UKmSLRBRJXOMwHaE6?w=230&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 41,
    name: "Sunrise Suites",
    country: "China",
    location: "Beijing",
    description: "A luxurious stay with breathtaking views.",
    price: 213.27,
    comments: "The view is stunning, and the service was exceptional.",
    rating: 4.7,
    rooms: 90,
    amenities: ["Wi-Fi"],
    image:
      "https://tse2-mm.cn.bing.net/th/id/OIP-C.zeU_5CkyJ5i25pTKyOdo8gHaE8?w=269&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 42,
    name: "Harmony Inn",
    country: "USA",
    location: "Los Angeles",
    description:
      "Located in the bustling city center, perfect for business travelers.",
    price: 217.35,
    comments: "Great location for exploring the city, with modern facilities.",
    rating: 4.8,
    rooms: 91,
    amenities: ["Wi-Fi", "Parking"],
    image:
      "https://tse1-mm.cn.bing.net/th?id=OIF-C.KjXr%2bzRvkSH8vDXC7AtT4w&w=282&h=188&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 43,
    name: "Ocean Breeze Hotel",
    country: "France",
    location: "Lyon",
    description: "Experience serenity by the riverside.",
    price: 221.43,
    comments: "A peaceful escape with excellent local cuisine.",
    rating: 4.8,
    rooms: 92,
    amenities: ["Wi-Fi", "Parking", "Pool"],
    image:
      "https://tse2-mm.cn.bing.net/th/id/OIF-C.8TVshsLpibzaQwHqdDHvuw?w=254&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 44,
    name: "Mountain Retreat",
    country: "Japan",
    location: "Hokkaido",
    description: "Wake up to ocean waves at this cozy hotel.",
    price: 225.51,
    comments: "The ocean view was spectacular, and the staff were kind.",
    rating: 4.8,
    rooms: 93,
    amenities: ["Wi-Fi", "Parking", "Pool", "Gym"],
    image:
      "https://tse4-mm.cn.bing.net/th?id=OIF-C.xXE%2fUG6vtuXwMBjKkzokQw&w=156&h=182&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 45,
    name: "Urban Oasis",
    country: "Australia",
    location: "Sydney",
    description: "A hidden gem nestled in the mountains.",
    price: 229.59,
    comments: "Charming and serene atmosphere with outstanding scenery.",
    rating: 4.8,
    rooms: 94,
    amenities: ["Wi-Fi", "Parking", "Pool", "Gym", "Spa"],
    image:
      "https://tse3-mm.cn.bing.net/th/id/OIF-C.Xpah5vrpIj15EN5N2dAyXg?w=270&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 46,
    name: "Riverfront Lodge",
    country: "India",
    location: "Mumbai",
    description: "Stay near famous attractions with luxurious amenities.",
    price: 233.67,
    comments: "A must-stay for visitors, close to attractions.",
    rating: 4.9,
    rooms: 95,
    amenities: ["Wi-Fi"],
    image:
      "https://tse2-mm.cn.bing.net/th/id/OIF-C.gTjZKXTEaz3RZDge2SNNzw?w=206&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 47,
    name: "Golden Gate Resort",
    country: "Germany",
    location: "Frankfurt",
    description:
      "An urban retreat with modern design and vibrant nightlife nearby.",
    price: 237.76,
    comments: "Perfect for those looking for nightlife and comfort.",
    rating: 4.9,
    rooms: 96,
    amenities: ["Wi-Fi", "Parking"],
    image:
      "https://tse1-mm.cn.bing.net/th?id=OIF-C.G9S8Ej%2f91XQmSXPem5yBGQ&w=243&h=196&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 48,
    name: "Cultural Haven Hotel",
    country: "Brazil",
    location: "Salvador",
    description:
      "Immerse yourself in the rich local culture while enjoying modern comforts.",
    price: 241.84,
    comments: "A great location near historical sites, with friendly staff.",
    rating: 4.9,
    rooms: 97,
    amenities: ["Wi-Fi", "Parking", "Pool"],
    image:
      "https://tse1-mm.cn.bing.net/th?id=OIF-C.UyQzaMx%2bRueuukLbMHbH%2fg&w=285&h=196&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 49,
    name: "Starlight Grand",
    country: "South Africa",
    location: "Cape Town",
    description: "A high-end hotel ideal for business and leisure.",
    price: 245.92,
    comments: "Top-notch service with luxurious amenities.",
    rating: 5.0,
    rooms: 98,
    amenities: ["Wi-Fi", "Parking", "Pool", "Gym"],
    image:
      "https://tse2-mm.cn.bing.net/th/id/OIP-C.F-hnVTnTQSVMWrzdDjUZXAHaFY?w=295&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id: 50,
    name: "Forest Whisper Inn",
    country: "Canada",
    location: "Vancouver",
    description: "A cozy stay near famous festivals.",
    price: 250.0,
    comments: "Perfect for winter vacations with charming interiors.",
    rating: 5.0,
    rooms: 99,
    amenities: ["Wi-Fi", "Parking", "Pool", "Gym", "Spa"],
    image:
      "https://img-md.veimg.cn/meadinindex/img5/2022/8/FE49FC7C4FE843F2ADAFA89786C3EB5C.jpg",
  },
];
